name: release
on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  release:
    name: x86_64-pc-windows-msvc
    runs-on: windows-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          target: x86_64-pc-windows-msvc

      - name: Setup Cache
        uses: Swatinem/rust-cache@v2

      - name: Build Binary
        run: cargo build --release --locked --target=x86_64-pc-windows-msvc --color=always --verbose

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: x86_64-pc-windows-msvc
          path: |
            ./target/x86_64-pc-windows-msvc/release/lol_account_manager_v2.exe

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./target/x86_64-pc-windows-msvc/release/lol_account_manager_v2.exe
